added doubt tags for personal messages by bot
devs-nest/discord-bot pull request #37
Opened 2021-02-14 04:28 UTC by Aarush-Goyal

## Feature description

If a person is not aware of the bot commands to ask a doubt then the bot will detect that the person has doubt and dm him the command and its use case.

## Solution description

I have made a list of doubt tags and have run a for loop in the event of `on_message` so when anyone messages a keyword from the tag list then a dm will be sent to the user.

## Output Screenshots

![image](https://user-images.githubusercontent.com/64161383/107868509-d7dcce80-6eaa-11eb-9e81-b872fa32aeb5.png)

## Address affected and ensured

`on_messages` function is affected and the file `event.py`

2021-02-14 11:16 UTC, vaibhav353 commented on event.py
> +        + "DN bot is always there to help and make your learning fun. Use the below commands for smooth experience on the platform \n"
80 char limit

2021-02-14 11:17 UTC, vaibhav353 commented on event.py
> +        url='https://cdn.wayscript.com/blog_img/83/DiscordBotThumb.png'
Let's have a different file where we are storing URLs.
Or name this as URL_SOME_NAME = 'https://cdn.wayscript.com/blog_img/83/DiscordBotThumb.png' and the use this variable.

2021-02-14 11:18 UTC, vaibhav353 commented on event.py
> +            asyncio.ensure_future(
Why did you break it into 2 lines?

2021-02-14 11:19 UTC, vaibhav353 commented on event.py
> +                "If you wanted to ask a doubt you can use the command ``` dn-mark-doubt Q<id> ``` to mark it as a doubt :innocent:")
80 char limit

2021-02-14 11:20 UTC, vaibhav353 reviewed
Minor nitpicks

2021-02-27 18:13 UTC, ShipraShalini requested changes

2021-02-27 18:13 UTC, ShipraShalini commented on event.py
> +doubt_tags = ["doubt", "problem", "doubts", "question"]
Create a new file `constants.py` and move this there. Also, PEP8 recommends using uppercase for constants.
https://www.python.org/dev/peps/pep-0008/#constants

2021-02-27 18:13 UTC, ShipraShalini commented on event.py
> +    if message.content.startswith('dn-mark-undone'):
[black](https://github.com/psf/black) will revert this change.

2021-02-27 18:13 UTC, ShipraShalini commented on event.py
> +            except:
It's never a good idea to catch a naked exception, it will catch even the system errors like `MemoryError`. Please narrow it down to the exceptions that this statement can produce and only catch those.

2021-02-27 18:13 UTC, ShipraShalini commented on event.py
> +                "If you wanted to ask a doubt you can use the command ``` dn-mark-doubt Q<id> ``` to mark it as a doubt :innocent:")
If there are multiple doubt tags in the message, like "I have a doubt in question" then this message will be sent twice. I don't this it's desirable, please add a `break` statement if that it so.

2021-02-27 19:27 UTC, ShipraShalini commented on event.py
> +                "If you wanted to ask a doubt you can use the command ``` dn-mark-doubt Q<id> ``` to mark it as a doubt :innocent:")
The message can be improved to:
```If you want to clarify a doubt, you can use the command ```dn-mark-doubt Q<id>``` to mark it as doubt. :innocent:"

2021-03-05 01:28 UTC, closed without merging