The big refractor utils
devs-nest/discord-bot pull request #58
Opened 2021-06-04 14:52 UTC by Adhikram

2021-06-04 17:11 UTC, patheticGeek requested changes
Noice work :+1:

2021-06-04 17:11 UTC, patheticGeek commented on services/content.py
> +from utils.inputDm import take_input_dm
dont use camel case, use snake case :snake:

2021-06-04 17:11 UTC, patheticGeek commented on services/group.py
> +from utils.dataNotFound import data_not_found
Use snake case here too

2021-06-04 17:11 UTC, patheticGeek commented on utils/inputDm.py
> +        user_input = False
Remove extra empty lines and return inside try catch instead of at end and use `None` instead of `False`

2021-06-05 04:31 UTC, kaydee0502 commented on api/request.py
Too many camel cases :eyes:

2021-06-05 06:35 UTC, merged

2021-06-05 06:37 UTC, patheticGeek commented on api/request.py
yeah ik, will be refactored further